### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/service.iptv.manager#13]
Our current logo doesn't spark much joy... We need a better one.

![Logo](https://raw.githubusercontent.com/add-ons/service.iptv.manager/master/resources/icon.png)

**Comment by piejanssens** [comment]
![ipvr manager icon](https://user-images.githubusercontent.com/829098/82834456-72caee00-9ec1-11ea-80f7-046d4d49c47b.png)

**Comment by piejanssens** [comment]
https://github.com/add-ons/service.iptv.manager/pull/22
