### ISSUE TITLE
Various todos and ideas

### ISSUE THREAD

**Issue by michaelarnauts** [add-ons/service.iptv.manager#2]
TODO:
* [ ] Implement refreshing logic (maybe with a force refresh somewhere, in a settings page?)
  * Don't refresh when playing, since we currently refresh by stopping and starting `pvr.iptvsimple`.
* [x] Implement option to configure IPTV Simple trough the settings. This should not be done automatically.

IDEAS:
* ~Consider to have the add-on specify a preferred channel number.~
* Implement a context menu in the Guide to play specific episodes (for Leia), or jump directly to the Program in the Addon (like https://github.com/michaelarnauts/context.pvr.justmissed).

**Comment by dagwieers** [comment]
Also see https://github.com/add-ons/service.iptv.manager/wiki/Roadmap

**Comment by michaelarnauts** [comment]
I've created #6 to track this further.
