### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by piejanssens** [add-ons/service.iptv.manager#21]
Is there a possibility for iptv mgr to integrate with IPTV recorder?

There doesn't seem to be a lot of dev activity on that recorder add-on.
I wonder if this would work with Widevine DRM streams too (Yelo).

https://forum.kodi.tv/showthread.php?tid=329991

**Comment by michaelarnauts** [comment]
This is using ffmpeg to record, so it will only work when using real internet streams, not trough the plugin:// URLs that we are using.

Also, I don't want to go that route since it's against the terms of use of the services.
