### ISSUE TITLE
Starting a live stream takes 5 seconds or more

### ISSUE THREAD

**Issue by dagwieers** [add-ons/service.iptv.manager#28]
Now that we have a bunch of live streams listed in Kodi using **pvr.iptvsimple**, the user experience is not that great when channel hopping. It takes 5 seconds or more switching from one channel to the next, which is poor TV behaviour.

*(The same is true for any stream, whether it is Netflix or another VOD content provider)*

Kodi takes a lot longer to start playback, whereas other devices and [online players](https://github.com/add-ons/best-practices/wiki/Streaming-issues) start playback immediately.

We should be able to do better.

**Comment by michaelarnauts** [comment]
Streams for VRT Nu are quite fast, but I also see that VTM Go streams can take up to a few seconds to start. There might be improvements we can do there.

**Comment by dagwieers** [comment]
@davilla I remember you mentioned something about this, e.g. that we should start playback immediately, but I cannot find the reference to those comments. If I remember correctly, can you maybe elaborate here?

**Comment by mediaminister** [comment]
If you input a number, you also have to input enter to zap immediately.

**Comment by dagwieers** [comment]
@mediaminister I know.

**Comment by dagwieers** [comment]
I hadn't clarified that disabling DRM makes a huge difference (on RPI at least).
So this is related to ISA or ISH, or both. But even disabling ISH doesn't make a noticable difference. So most of the slowness is due to ISA/Widevine.

Without DRM audio starts earlier than video, which gives the impression to be faster too. But even switching between Eén and Canvas without DRM is about 2  seconds for audio and 3.5 seconds for video.

With DRM video starts before audio (after 5 seconds) andt it takes 6.5 seconds before things are working fine.

Starting live TV via VRT NU add-on is slower than via IPTV Manager. (I guess the caching will help there).

*(These timings were measured with a chronometer...)*

During testing I also noticed that after zapping once, I can no longer zap to another channel.

**Comment by mediaminister** [comment]
Is this a Raspberry Pi issue or does this happen on other devices too? Which Raspberry Pi version?
Does this happen running Chromium with Widevine and browsing to VRT NU website on Raspberry Pi?

Meanwhile I added caching for the livestream jsons, which should be ready to merge: https://github.com/add-ons/plugin.video.vrt.nu/pull/772

Does caching the livestream json allows faster zapping on Raspberry Pi?

**Comment by dagwieers** [comment]
FYI Other projects are also looking at channel switching time: https://github.com/xbmc/inputstream.ffmpegdirect/issues/57

**Comment by michaelarnauts** [comment]
I would rather close this issue. Any optimisations of speed have to be with caching of tokens used for a live stream at the Add-on side. IPTV Manager isn't in the code path when switching channels or using the Guide.

**Comment by dagwieers** [comment]
Correct, although:
- Most people would blame IPTV Manager if this is slow
- This issue could be the issue tracking slow playback issues in add-ons
