### ISSUE TITLE
Error thrown when no addon supporting IPTV Manager installed

### ISSUE THREAD

**Issue by im85288** [add-ons/service.iptv.manager#36]
Here are a few things I have noticed/think can be improved:

-  When you install IPTV Manager and no supporting addon for syncing is available an exception is shown in Kodi.
- When you go to settings and ask it to setup Simple IPTV when Simple IPTV is not installed, it states it could not configure the settings and in the background shows the dialog to install the Simple IPTV addon.

Would it be possible to have IPTV Manager Auto install the Simple IPTV addon?

Would it be possible to allow another addon to call IPTV Manager to setup usage via Simple IPTV? My thinking here is that it will be more user friendly for a user not to have to go to the settings and setup iptv simple for control by iptv manager. Ideally all the user should need to do is install the addon doing the synching which would then take care of everything else.

Lastly is it feasible/possible to support service addons? Initially I only wanted my addon to be a service addon and not to be a plugin source (providing video)..but I had to set it up for video to integrate correctly with this addon.

Thanks 😊

**Comment by michaelarnauts** [comment]
> Here are a few things I have noticed/think can be improved:
> 
> * When you install IPTV Manager and no supporting addon for syncing is available an exception is shown in Kodi.

This sounds like a bug. I'll check this. A lot of things are currently untested or not handled correctly.

> * When you go to settings and ask it to setup Simple IPTV when Simple IPTV is not installed, it states it could not configure the settings and in the background shows the dialog to install the Simple IPTV addon.
> Would it be possible to have IPTV Manager Auto install the Simple IPTV addon?

I don't think this is possible. We do enable it if it is disabled.

> Would it be possible to allow another addon to call IPTV Manager to setup usage via Simple IPTV? My thinking here is that it will be more user friendly for a user not to have to go to the settings and setup iptv simple for control by iptv manager. Ideally all the user should need to do is install the addon doing the synching which would then take care of everything else.

You only need to setup IPTV Manager once, so it should be done when you install it. I'm not sure if the automatic configuration is something that we can keep. It is conflicting with the guidelines of the Kodi Addons of Team Kodi. Currently, you should be able to call `RunScript(service.iptv.manager,setup-iptv-simple)` to setup IPTV Simple though.

> Lastly is it feasible/possible to support service addons? Initially I only wanted my addon to be a service addon and not to be a plugin source (providing video)..but I had to set it up for video to integrate correctly with this addon.

Hmm, not sure. We need to be able to call an endpoint currently, but I don't think it needs to be present in the Kodi UI. It might be possible to use something like `<extension point="xbmc.python.library" library="default.py"/>` in your addon.xml.

> 
> Thanks

You're welcome :)

**Comment by michaelarnauts** [comment]
> > When you install IPTV Manager and no supporting addon for syncing is available an exception is shown in Kodi.
> 
> This sounds like a bug. I'll check this. A lot of things are currently untested or not handled correctly.
> 

@im85288 I could not find an issue here. Can you post the exception you get?

**Comment by im85288** [comment]
@michaelarnauts sure I’ll see if I can reproduce and send it across.

**Comment by im85288** [comment]
@michaelarnauts Here you go, for me it was easy to reproduce...just delete this addon (clicking yes to remove all settings), assure there are no providers installed and the exception occurs:

```
020-06-19 15:14:04.907 T:215250378   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: 'addons'
                                                   Traceback (most recent call last):
                                                     File "/Users/ianmclaughlin/Library/Application Support/Kodi/addons/service.iptv.manager/service.py", line 8, in <module>
                                                       service.run()
                                                     File "/Users/ianmclaughlin/Library/Application Support/Kodi/addons/service.iptv.manager/resources/lib/service.py", line 56, in run
                                                       BackgroundService().run()
                                                     File "/Users/ianmclaughlin/Library/Application Support/Kodi/addons/service.iptv.manager/resources/lib/service.py", line 34, in run
                                                       Addon.refresh()
                                                     File "/Users/ianmclaughlin/Library/Application Support/Kodi/addons/service.iptv.manager/resources/lib/modules/addon.py", line 59, in refresh
                                                       addons = cls.detect_iptv_addons()
                                                     File "/Users/ianmclaughlin/Library/Application Support/Kodi/addons/service.iptv.manager/resources/lib/modules/addon.py", line 116, in detect_iptv_addons
                                                       for row in result['result']['addons']:
                                                   KeyError: 'addons'
                                                   -->End of Python script error report<--
```

**Comment by im85288** [comment]
For this part:

_When you go to settings and ask it to setup Simple IPTV when Simple IPTV is not installed, it states it could not configure the settings and in the background shows the dialog to install the Simple IPTV addon.
Would it be possible to have IPTV Manager Auto install the Simple IPTV addon?_
**I don't think this is possible. We do enable it if it is disabled.**

Maybe disable the link if Simple IPTV is not installed?

**Comment by im85288** [comment]
For this:

_Lastly is it feasible/possible to support service addons? Initially I only wanted my addon to be a service addon and not to be a plugin source (providing video)..but I had to set it up for video to integrate correctly with this addon._
**Hmm, not sure. We need to be able to call an endpoint currently, but I don't think it needs to be present in the Kodi UI. It might be possible to use something like <extension point="xbmc.python.library" library="default.py"/> in your addon.xml.**

I will give this a try thanks :)

**Comment by michaelarnauts** [comment]
@im85288 Sorry, it took a while look at this issue, it only happens when you have no addon at all installed with a `xbmc.python.pluginsource` entrypoint.

Now, I also mentioned that you might be able to use a `<extension point="xbmc.python.library" library="default.py"/>`, if you want to have an Addon that is compatible with IPTV Manager, but isn't visible in the UI, but that's not really true, since we filter out those addons. If this is really necessary, we could remove that filter, but that would require looping over all addons that are installed on the system.

**Comment by im85288** [comment]
@michaelarnauts No problem things are working fine for me, I think you can close this issue.
