### ISSUE TITLE
Watch programs from the past not working

### ISSUE THREAD

**Issue by iwanvandaele** [add-ons/service.iptv.manager#44]
How to watch programs from the past. I can see the past programs in my channel guide, but the past is blue and i can't start the program. Is there something extra needed for that?

Regards

**Comment by iwanvandaele** [comment]
If you click on the program -> options and then play with iptv manager it's working.

**Comment by dagwieers** [comment]
@iwanvandaele That is how it should be used in Kodi v18.

**Comment by iwanvandaele** [comment]
K thx
