### ISSUE TITLE
Option to disable certain channels

### ISSUE THREAD

**Issue by piejanssens** [add-ons/service.iptv.manager#48]
Use case: multiple add-ons offering the same channels (e.g. Yelo vs. VTM Go / VRT Nu / Regio)
One would generally prefer the source providing the best quality and disable the other channels from appearing in PVR.

**Comment by michaelarnauts** [comment]
This is related to #43 but you can already disable channels at the moment. Pick manage channels in the context menu on in the Guide, and in that dialog, you can disable channels.

**Comment by piejanssens** [comment]
OK Closing this then. Thanks for the context tip @michaelarnauts.

**Comment by dagwieers** [comment]
What would be useful is that the add-on providing the channel would be visible somewhere. This way I can select the one I need for my purpose, now it is just a big guess.

**Comment by michaelarnauts** [comment]
I'll try to add this to the user guide later.

**Comment by michaelarnauts** [comment]
@dagwieers that would be nice indeed, but I don't know how this can be done. Is the URL visible somewhere in that dialog?

**Comment by dagwieers** [comment]
I think somehow IPTV Simple should make this possible via metadata for this purpose.
Or we could add a small piece of information to the description, just the *most important bit*, like `vrt.nu`, `yelo`, `vrt.radio`

**Comment by michaelarnauts** [comment]
See: https://github.com/add-ons/service.iptv.manager/wiki/Usage-(NL)#kanalen-beheren
