### ISSUE TITLE
Red Bull TV -> add-ons

### ISSUE THREAD

**Issue by piejanssens** [add-ons/service.iptv.manager#50]
@dagwieers Ik heb IPTV Manager ondersteuning toegevoegd aan mijn Red Bull TV add-on.
De add-on heeft nog serieus refactoring nodig, maar hij doet het goed.
Zou ik deze add-on nieuwe thuis kunnen geven onder https://github.com/add-ons?
https://github.com/piejanssens/plugin.video.redbulltv

Plan is om deze te submitted bij Matrix b1.

<img width="1440" alt="Schermafbeelding 2020-10-24 om 23 05 53" src="https://user-images.githubusercontent.com/829098/97093952-6c979400-1650-11eb-987a-ee1b32903a13.png">

**Comment by michaelarnauts** [comment]
Dat kan. Ik heb dan rechten nodig op je repo om die naar de add-ons org te moven.

**Comment by dagwieers** [comment]
@piejanssens Ik zag dat het geforked is van een andere add-on. Wordt de originele add-on niet meer gemaintained?
