### ISSUE TITLE
IPTV does not detect Yelo channels

### ISSUE THREAD

**Issue by emversch** [add-ons/service.iptv.manager#53]
Yelo by shycoderX version 0.0.9 is not detected when scanning for channels. When choosing "refresh channels and guide now..." only VRT NU and VRT Radio are detected, but not Yelo.

Installed version of IPTV Manager is 0.2.1
Running LibreELEC 9.2.6 on Raspberry Pi 4 2GiB

**Comment by michaelarnauts** [comment]
I think you need version 1.0, maybe it isn't released yet. You should try with the latest code of Yelo.
