### ISSUE TITLE
Add ability to use a UTF8-BOM m3u

### ISSUE THREAD

**Issue by andreassamitsch** [add-ons/service.iptv.manager#56]
Ability to use a UTF8-BOM m3u needed.
At the moment it is inerpreting the BOM Signature as characters and says it is no playlist file.

**Comment by dagwieers** [comment]
IPTV Manager does not support M3U files at the moment. Maybe you are confusing the IPTV Manager add-on with the IPTV Simple PVR add-on ?

**Comment by michaelarnauts** [comment]
Correct, feel free to reopen or comment in case you have an issue with this add-on. Please indicate the steps you took and provide the Kodi log.

Thanks for taking the time to report an issue though.
