### ISSUE TITLE
Guide and channel update

### ISSUE THREAD

**Issue by gitovino** [add-ons/service.iptv.manager#60]
Hi there,

Most of the time the channels and guide do not refresh. I selected to do a refresh every hour. When I do a manual refresh most of the channels do this but the Yelo channel does not.

Is this a known issue?

Thanks for looking into this.

**Comment by michaelarnauts** [comment]
I think you better report this at the Yelo TV addon repository: https://github.com/add-ons/plugin.video.yelo

Note that IPTV Manager only refreshes the guide when nothing is playing.

**Comment by gitovino** [comment]
Moving it to the Yelo TV addon repository.
