### ISSUE TITLE
New supported addon

### ISSUE THREAD

**Issue by BreizhReloaded** [add-ons/service.iptv.manager#78]
Hello guys,

May I update the supported addons list to add my new [Orange TV France addon](https://github.com/BreizhReloaded/plugin.video.orange.fr)?

Thanks,

Breizh

**Comment by dagwieers** [comment]
I added it, both for live TV as well as VOD.

**Comment by BreizhReloaded** [comment]
Perfect, thank you @dagwieers!

**Comment by dagwieers** [comment]
@BreizhReloaded Did you try to edit it yourself? We allow edits to the Wiki from the community, but up to this point nobody did ;-) https://github.com/add-ons/service.iptv.manager/wiki/Supported-Addons

**Comment by BreizhReloaded** [comment]
I tried and was able to, but I was to shy to actually update the list :D
