### ISSUE TITLE
Only one day back in Timeline? 

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/service.iptv.manager#79]
Hello,
Wonderful add-on. 
But seems to me one can only go 1 day back in time in the grid. 
Am I doing anything wrong?

**Comment by michaelarnauts** [comment]
Probably not, this depends on the data that is given by the Add-on itself. I do remember that Kodi can cache old information, so by tomorrow, you can probably go back one more day.

If i remember correctly, vtm go and vrt nu provide data for 3 days (yesterday, today & tomorrow).

**Comment by Rvhalewyn** [comment]
Thanks Michaël. Set the epg buffering to ON. Hope it will work, because going back only one day is not very practical... 

Can hardly wait until you implement auvio, npo, France TV,... 

Wonderful work you're doing. 


Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: "Michaël Arnauts" <notifications@github.com>
Verzonden: 1 maart 2021 17:02:51 CET
Aan: "add-ons/service.iptv.manager" <service.iptv.manager@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/service.iptv.manager] Only one day back in Timeline?  (#79)

Probably not, this depends on the data that is given by the Add-on itself. I do remember that Kodi can cache old information, so by tomorrow, you can probably go back one more day.

If i remember correctly, vtm go and vrt nu provide data for 3 days (yesterday, today & tomorrow).

**Comment by michaelarnauts** [comment]
You should take a look at Catch-up TV & More. It has support for all the
channels you've mentioned, and also supports IPTV Manager.

Op ma 1 mrt. 2021 19:28 schreef Rvhalewyn <notifications@github.com>:

**Comment by Rvhalewyn** [comment]
Oh sorry.
Took a closer look at the new Catch up version.
Hadn't noticed the Manager integration.
All programmes were OFF in the selection. 
Works fine now! Great job! 

Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: "Michaël Arnauts" <notifications@github.com>
Verzonden: 1 maart 2021 21:13:41 CET
Aan: "add-ons/service.iptv.manager" <service.iptv.manager@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/service.iptv.manager] Only one day back in Timeline?  (#79)

You should take a look at Catch-up TV & More. It has support for all the
channels you've mentioned, and also supports IPTV Manager.

Op ma 1 mrt. 2021 19:28 schreef Rvhalewyn <notifications@github.com>:

**Comment by Rvhalewyn** [comment]
As you are being so kind, Michaël, one remark about NPO.
Catch-up gives no entry for username & password there. As I have an NPO Plus registration, I get HD quality on Retrospect. On Catch-up, as I can't register, it's SD.

As you have excellent contacts within Hithub, perhaps you might introduce that issue? Or perhaps integrate Retrospect? 

Kind regards
Rudy Vanhalewyn 
Winston Churchilllaan 23 bus 14 
B-8300 Knokke-Heist 
BELGIUM 



-------- Origineel bericht --------
Van: "Michaël Arnauts" <notifications@github.com>
Verzonden: 1 maart 2021 21:13:41 CET
Aan: "add-ons/service.iptv.manager" <service.iptv.manager@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/service.iptv.manager] Only one day back in Timeline?  (#79)

You should take a look at Catch-up TV & More. It has support for all the
channels you've mentioned, and also supports IPTV Manager.

Op ma 1 mrt. 2021 19:28 schreef Rvhalewyn <notifications@github.com>:

**Comment by Rvhalewyn** [comment]
Sorry for bothering you again. 

Very busy implementing CatchUp in Simple iptv. There seems to be a problem with the French programs, I saw it on the Catch-up Github page. Can open only France3.

Weird is that I get no EPG for all French and NPO channels, Belgian work fine. I copied and opened epg.xml, and found all EPG information, so there must be a missing link. I emptied the EPG buffer and rebooted, no change.

Can't help thinking Catch-up is having serious troubles lately. Implementing France TV and Retrospect would be more stable, I suppose, but I'm a total ignorant in programming. 

Met vriendelijke groeten
Rudy Vanhalewyn
Contactpersoon voor België van
Stichting Projecthulp Suriname
Winston Churchilllaan 23 bus 14
B-8300 Knokke-Heist

tel. +32 50 94 61 28 of +32 496 84 72 74
tel. vanuit Suriname 750 37 47
tel. vanuit Nederland +31 6 377 22 746
Viber +316 377 22 746
WhatsApp +316 377 22 746
sip:rvhalewyn@pbxes.org 
LinkedIn Rudy Vanhalewyn


-------- Origineel bericht --------
Van: "Michaël Arnauts" <notifications@github.com>
Verzonden: 1 maart 2021 21:13:41 CET
Aan: "add-ons/service.iptv.manager" <service.iptv.manager@noreply.github.com>
CC: Rvhalewyn <Rudy.Vanhalewyn@gmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [add-ons/service.iptv.manager] Only one day back in Timeline?  (#79)

You should take a look at Catch-up TV & More. It has support for all the
channels you've mentioned, and also supports IPTV Manager.

Op ma 1 mrt. 2021 19:28 schreef Rvhalewyn <notifications@github.com>:

**Comment by michaelarnauts** [comment]
I highly suggest to take a look at the Catch-up TV & More GitHub page: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore

Maybe your issue is already reported there.
