### ISSUE TITLE
No EPG for Arte and TV5Monde 

### ISSUE THREAD

**Issue by Rvhalewyn** [add-ons/service.iptv.manager#83]
EPG works fine for Belgian and French Catchup TV add-on channels, but the Guide remains blank for Arte and TV5Monde.
Kodi 18.9 on Libreelec.

**Comment by dagwieers** [comment]
This is unrelated to IPTV Manager. You will have to discuss this with the add-on providing these channels.

Not every add-on/channel provides IPTV Manager with EPG data, so we cannot show what we do not receive.

**Comment by dagwieers** [comment]
I noticed you opened a ticket at: https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/490

Closing this one instead :-)
