### ISSUE TITLE
log filling with info when postponing

### ISSUE THREAD

**Issue by rafhtl** [add-ons/service.iptv.manager#85]
INFO : [service.iptv.manager] [resources.lib.modules.iptvsimple] Postponing restart of Simple IPTV since it is currently in use

Hi thank you for the wonderful work on the addon
Ive noticed streaming for a long time that pvr is correctly postponing epg, but it is filling log with the message
can you help me?
thank you

**Comment by michaelarnauts** [comment]
This will be checked every 30 seconds. We could drop the log altogether, but is it actually a problem?

**Comment by rafhtl** [comment]
Well After I left the channel playing
I came back after 8 h or so and it had gotten to 1G
For rpi with SD... yes it could actually be a problem
Thank you

**Comment by michaelarnauts** [comment]
> Well After I left the channel playing
> I came back after 8 h or so and it had gotten to 1G
> For rpi with SD... yes it could actually be a problem
> Thank you

Hmm, I see. That's actually quite a lot. I think it makes more sense to keep this message, but change it to a debug log instead. You shouldn't use debug logging in production, so that will fix the issue for you.

**Comment by rafhtl** [comment]
thank you
so if I keep
<setting id="debug_logging" default="true">false</setting>
I should not be seeing it anymore
How do I update to new version?
thank you

**Comment by rafhtl** [comment]
I fixed  my local with your fix and testing
thank you
